function [matched_keypoints_query,matched_keypoints_database] = getMatchedPoints(...
                keypoints_query, keypoints_database, ...  
                descriptors_query, descriptors_database, hyperparameters)

    % first figure out which feature detection algo was used
    if (hyperparameters.featDetec_algo == "SIFT")
        [matched_keypoints_query, matched_keypoints_database] = ...
            getMatchedPoints_sift(  keypoints_query, keypoints_database, ...  
                                    descriptors_query, descriptors_database, ...
                                    hyperparameters.match_threshold, ...
                                    hyperparameters.match_max_ratio, ...
                                    hyperparameters.match_unique);
    elseif (hyperparameters.featDetec_algo == "Harris")
        [matched_keypoints_query, matched_keypoints_database] = ...
            getMatchedPoints_harris(keypoints_query, keypoints_database, ...  
                                    descriptors_query, descriptors_database, ...
                                    hyperparameters.match_lambda);
    end
end