function [kpts, desc] = featDetect(image, hyperparameters)
    % check which algo to use
    if (hyperparameters.featDetec_algo == "SIFT")
        [kpts, desc] = sift(image, ...
                            hyperparameters.sift_num_scales, ...
                            hyperparameters.sift_sigma, ...
                            hyperparameters.sift_contrast_threshold);
    elseif (hyperparameters.featDetec_algo == "Harris")
        [kpts, desc] = harris(image, ...
                            hyperparameters.harris_min_quality, ... 
                            hyperparameters.harris_filer_size);
    elseif (hyperparameters.featDetec_algo == "FAST")
        [kpts, desc] = fast(image, ...
                            hyperparameters.fast_min_quality, ... 
                            hyperparameters.fast_min_contrast);
    else
        % output error
        error('The given feature detection method is not valid');
    end
end